theme: jekyll-theme-tactile

sidebar:
  - label: Data Processing
    children:
      - intro
      - local-environment
      - process-data
      - individual-functions
  -label: Shiny Deployment
    - shiny
